SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SELECT * FROM tienda.producto;
SELECT nombre, precio, precio/1.015 FROM tienda.producto;
SELECT nombre, precio AS euros, precio/1.015 AS "dòlars nord-americans" FROM tienda.producto;
SELECT UPPER(nombre), precio FROM tienda.producto;
SELECT LOWER(nombre), precio FROM tienda.producto;
SELECT nombre, UPPER(left(nombre,2)) FROM tienda.fabricante;
SELECT nombre, ROUND(precio,2) FROM tienda.producto;
SELECT nombre, CEIL(precio) FROM tienda.producto;
SELECT fabricante.codigo FROM tienda.fabricante, tienda.producto WHERE producto.codigo !=' ';
SELECT DISTINCT fabricante.codigo FROM tienda.fabricante, tienda.producto WHERE producto.codigo !=' ';
SELECT nombre FROM tienda.fabricante ORDER BY nombre ASC;
SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM tienda.producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM tienda.fabricante LIMIT 5;
SELECT * FROM tienda.fabricante LIMIT 3, 3;
SELECT nombre, precio FROM tienda.producto GROUP BY precio ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM tienda.producto GROUP BY precio ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM tienda.fabricante WHERE codigo LIKE "2";
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante;
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante ORDER BY fabricante.nombre ASC;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM tienda.producto, tienda.fabricante;
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE precio = (SELECT MIN(precio) FROM tienda.producto);
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE precio = (SELECT MAX(precio) FROM tienda.producto);
SELECT producto.nombre, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre='Lenovo';
SELECT producto.nombre, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre='Crucial' AND Precio>200;
SELECT producto.nombre, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre='Asus' OR fabricante.Nombre='Hewlett-Packard' OR fabricante.Nombre='Seagate';
SELECT producto.nombre, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre IN ('Asus','Hewlett-Packard','Seagate');
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE RIGHT(fabricante.nombre, 1) LIKE 'e';
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE '%w%' OR 'W%' OR '%w';
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE precio > 180 ORDER BY precio DESC, producto.nombre ASC;
SELECT fabricante.codigo, fabricante.nombre FROM tienda.fabricante, tienda.producto WHERE producto.codigo NOT LIKE ' ';
SELECT fabricante.nombre, producto.nombre FROM tienda.fabricante, tienda.producto;
SELECT fabricante.nombre FROM tienda.fabricante, tienda.producto WHERE producto.codigo LIKE ' ';
SELECT producto.nombre, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE 'Lenovo';
SELECT * FROM tienda.producto, tienda.fabricante WHERE precio LIKE (SELECT MAX(precio) FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE 'Lenovo' AND precio LIKE (SELECT MAX(precio) FROM tienda.producto));
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE 'Lenovo' AND precio LIKE (SELECT MAX(precio) FROM tienda.producto);
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE 'Hewlett-Packard' AND precio LIKE (SELECT MIN(precio) FROM tienda.producto);
SELECT * FROM tienda.producto, tienda.fabricante WHERE precio >= (SELECT MAX(precio) FROM tienda.producto, tienda.fabricante WHERE fabricante.nombre LIKE 'Lenovo' AND precio LIKE (SELECT MAX(precio) FROM tienda.producto));
SELECT fabricante.nombre, producto.nombre, precio FROM tienda.producto, tienda.fabricante WHERE precio > (SELECT AVG(precio) FROM tienda.producto WHERE fabricante.nombre LIKE 'Asus');